### PR TITLE
Add a makefile rule for building on OpenBSD

### PR DESCRIPTION
**Pull request by e-zk**

### CODE REVIEW

**Comment by e-zk** [comment]
Actually, to avoid having a rule for each possible OS Go supports why not have a generic  `build` rule that just uses the default GOOS/GOARCH on any system; let Go figure that out?

**Comment by nkanaev** [comment]
sounds good. `build_default` maybe?

**Comment by nkanaev** [comment]
https://github.com/nkanaev/yarr/commit/ffc506371c1835b90b4bfd3d5160348322a2426d should resolve this.

**Comment by e-zk** [comment]
Thanks!

**Pull request closed without merging**
